### PR TITLE
[Bugfix] Replaced & for fixing #28

### LINKED ISSUE #28: Calc Does Not Work
Calc Does Not Work
```
Traceback (most recent call last):
  File "beyn.py", line 120, in digitClicked
    digitValue = int(clickedButton.text())
ValueError: invalid literal for int() with base 10: '&2'
[1]    31390 abort (core dumped)  python3 beyn.py
```

i got this error when i click a number twice.

### PR DESCRIPTION
**Pull request by ghost**
Closes #28

### CODE REVIEW

**Comment by baoboa** [comment]
thank again.

**Comment by ghost** [comment]
Do you think merge it or close it? lol i really want be a pyqt5 contributor. :)

**Comment by baoboa** [comment]
done.

**Comment by baoboa** [comment]
At least you are a contributor to my private mirror. :)

**Comment by ghost** [comment]
:)

**Pull request merged**
